# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busshaming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='gtfs_agency_id',
            field=models.CharField(default='xxx', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_headsign',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_short_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='agency',
            unique_together=set([('gtfs_agency_id', 'feed_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together=set([('gtfs_route_id', 'feed_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='trip',
            unique_together=set([('gtfs_trip_id', 'version', 'route_id')]),
        ),
    ]
