# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busshaming', '0002_auto_20170811_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='slug',
            field=models.SlugField(default='xxx'),
            preserve_default=False,
        ),
    ]
