# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 23:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busshaming', '0005_auto_20170812_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='feed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='busshaming.Feed'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='stop',
            unique_together=set([('feed', 'gtfs_stop_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='tripstop',
            unique_together=set([('trip', 'stop', 'sequence')]),
        ),
    ]
