# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 03:56
from __future__ import unicode_literals

from django.contrib.postgres.operations import CreateExtension
import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busshaming', '0008_auto_20170819_0706'),
    ]

    operations = [
        CreateExtension('postgis'),
        migrations.AddField(
            model_name='stop',
            name='position',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
