# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 13:22
from __future__ import unicode_literals

from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('busshaming', '0009_stop_position'),
    ]

    operations = [
        CreateExtension('uuid-ossp'),
        migrations.CreateModel(
            name='RealtimeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('sequence', models.IntegerField()),
                ('arrival_time', models.DateTimeField()),
                ('arrival_delay', models.SmallIntegerField()),
                ('departure_time', models.DateTimeField()),
                ('departure_delay', models.SmallIntegerField()),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busshaming.Stop')),
                ('trip_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busshaming.TripDate')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='realtimeentry',
            unique_together=set([('trip_date', 'stop')]),
        ),
    ]
