# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busshaming', '0011_auto_20170827_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedtimetable',
            name='last_processed_zip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
