# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 05:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busshaming', '0012_feedtimetable_last_processed_zip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='url',
            new_name='route_url',
        ),
    ]
