# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-03 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busshaming', '0013_auto_20170917_0502'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_hash', models.CharField(max_length=64)),
                ('stop_sequence', models.TextField()),
                ('length', models.SmallIntegerField()),
                ('trip_headsign', models.CharField(blank=True, max_length=200, null=True)),
                ('trip_short_name', models.CharField(blank=True, max_length=200, null=True)),
                ('direction', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busshaming.Route')),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='stop_sequence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='busshaming.StopSequence'),
        ),
        migrations.AlterUniqueTogether(
            name='stopsequence',
            unique_together=set([('sequence_hash', 'route')]),
        ),
    ]
