# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-31 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busshaming', '0014_auto_20171203_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='last_processed_dump',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
