# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-01 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busshaming', '0016_tripdate_added_from_realtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='added_from_realtime',
            field=models.BooleanField(default=False),
        ),
    ]
