# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-07 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busshaming', '0017_trip_added_from_realtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealtimeProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('in_progress', models.DateTimeField()),
                ('last_processed_dump', models.CharField(blank=True, max_length=50, null=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busshaming.Feed')),
            ],
        ),
    ]
