# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-07 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busshaming', '0019_auto_20180107_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimeprogress',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='realtimeprogress',
            name='in_progress',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
