# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-13 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busshaming', '0020_auto_20180107_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='scheduled',
            field=models.BooleanField(default=True),
        ),
    ]
