# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-18 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busshaming', '0022_auto_20180115_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripdate',
            name='end_delay',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripdate',
            name='has_stats',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tripdate',
            name='max_delay',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripdate',
            name='middle_delay',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripdate',
            name='num_delay_stops',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripdate',
            name='num_realtime_stops',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripdate',
            name='num_scheduled_stops',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripdate',
            name='start_delay',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripdate',
            name='start_time',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='tripdate',
            name='sum_delay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripdate',
            name='sum_delay_squared',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
