# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-20 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busshaming', '0023_auto_20180118_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimeprogress',
            name='stats_completed',
            field=models.BooleanField(default=False),
        ),
    ]
