# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-20 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busshaming', '0024_realtimeprogress_stats_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='stopsequence',
            name='has_timepoints',
            field=models.BooleanField(default=True),
        ),
    ]
