# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-21 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busshaming', '0025_stopsequence_has_timepoints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripdate',
            name='has_stats',
        ),
        migrations.AddField(
            model_name='tripdate',
            name='avg_delay',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripdate',
            name='has_realtime_stats',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tripdate',
            name='has_start_middle_end_stats',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tripdate',
            name='is_stats_calculation_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tripdate',
            name='realtime_accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripdate',
            name='realtime_coverage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripdate',
            name='variance_delay',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
