# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-21 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busshaming', '0026_auto_20180121_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripdate',
            name='lower_quartile_delay',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripdate',
            name='median_delay',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripdate',
            name='min_delay',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripdate',
            name='upper_quartile_delay',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
