# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-21 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busshaming', '0027_auto_20180121_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripdate',
            name='early_count',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripdate',
            name='late_count',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripdate',
            name='ontime_count',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripdate',
            name='verylate_count',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
