# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-21 11:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busshaming', '0028_auto_20180121_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('num_scheduled_stops', models.PositiveIntegerField()),
                ('num_realtime_stops', models.PositiveIntegerField()),
                ('realtime_coverage', models.FloatField(blank=True, null=True)),
                ('realtime_accuracy', models.FloatField(blank=True, null=True)),
                ('early_count', models.IntegerField()),
                ('ontime_count', models.IntegerField()),
                ('late_count', models.IntegerField()),
                ('verylate_count', models.IntegerField()),
                ('count_has_start_middle_end_stats', models.IntegerField(default=False)),
                ('sum_start_delay', models.IntegerField(blank=True, null=True)),
                ('sum_middle_delay', models.IntegerField(blank=True, null=True)),
                ('sum_end_delay', models.IntegerField(blank=True, null=True)),
                ('num_delay_stops', models.PositiveIntegerField()),
                ('sum_delay', models.IntegerField()),
                ('sum_delay_squared', models.IntegerField()),
                ('max_delay', models.SmallIntegerField(blank=True, null=True)),
                ('min_delay', models.SmallIntegerField(blank=True, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busshaming.Route')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='routedate',
            unique_together=set([('route', 'date')]),
        ),
    ]
