# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-21 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busshaming', '0029_auto_20180121_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routedate',
            name='sum_delay_squared',
            field=models.BigIntegerField(),
        ),
    ]
