# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-21 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busshaming', '0030_auto_20180121_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='routedate',
            name='num_trips',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
