# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-30 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('busshaming', '0032_auto_20180122_0735'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteRanking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('timespan', models.PositiveSmallIntegerField(choices=[(1, 'DAY'), (2, 'SEVEN_DAYS'), (3, 'CALENDAR_MONTH')])),
                ('metric', models.PositiveSmallIntegerField(choices=[(1, 'MOST_ONTIME_TRIP_PERCENT'), (2, 'LEAST_ONTIME_TRIP_PERCENT'), (3, 'MOST_EARLY_TRIP_PERCENT'), (4, 'MOST_VERYLATE_TRIP_PERCENT')])),
                ('rank', models.PositiveSmallIntegerField()),
                ('display_rank', models.PositiveSmallIntegerField()),
                ('value', models.FloatField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busshaming.Route')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='routeranking',
            unique_together=set([('date', 'timespan', 'metric', 'rank')]),
        ),
        migrations.AlterIndexTogether(
            name='routeranking',
            index_together=set([('date', 'timespan', 'metric')]),
        ),
    ]
