# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-24 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busshaming', '0033_auto_20180130_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedtimetable',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
