# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-24 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busshaming', '0034_feedtimetable_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedtimetable',
            name='processed_watermark',
            field=models.DateTimeField(null=True),
        ),
    ]
