# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-24 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busshaming', '0035_feedtimetable_processed_watermark'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripdate',
            name='schedule_relationship',
            field=models.SmallIntegerField(choices=[('SCHEDULED', 1), ('ADDED', 2), ('UNSCHEDULED', 3), ('CANCELLED', 4)], default=1),
            preserve_default=False,
        ),
    ]
