# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-24 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busshaming', '0036_tripdate_schedule_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimeentry',
            name='schedule_relationship',
            field=models.SmallIntegerField(choices=[(1, 'SCHEDULED'), (2, 'ADDED'), (3, 'UNSCHEDULED'), (4, 'CANCELLED')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tripdate',
            name='schedule_relationship',
            field=models.SmallIntegerField(choices=[(1, 'SCHEDULED'), (2, 'ADDED'), (3, 'UNSCHEDULED'), (4, 'CANCELLED')]),
        ),
    ]
