# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-24 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busshaming', '0037_auto_20181124_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripdate',
            name='vehicle_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
