# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-24 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busshaming', '0038_tripdate_vehicle_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='realtimeentry',
            unique_together=set([('trip_date', 'stop', 'sequence')]),
        ),
    ]
