# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-27 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busshaming', '0040_auto_20181124_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteStopDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('scheduled_bus_count', models.PositiveSmallIntegerField()),
                ('realtime_bus_count', models.PositiveSmallIntegerField()),
                ('schedule_wait_time_seconds_total', models.PositiveSmallIntegerField()),
                ('schedule_wait_time_seconds_avg', models.PositiveSmallIntegerField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busshaming.Route')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busshaming.Stop')),
            ],
        ),
        migrations.CreateModel(
            name='RouteStopHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('hour', models.PositiveSmallIntegerField(db_index=True)),
                ('scheduled_bus_count', models.PositiveSmallIntegerField()),
                ('realtime_bus_count', models.PositiveSmallIntegerField()),
                ('expected_wait_next_day', models.BooleanField(default=False)),
                ('realtime_wait_next_day', models.BooleanField(default=False)),
                ('expected_random_wait_time_seconds', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('realtime_random_wait_time_seconds', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busshaming.Route')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busshaming.Stop')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='routestophour',
            unique_together=set([('route', 'stop', 'date', 'hour')]),
        ),
        migrations.AlterUniqueTogether(
            name='routestopday',
            unique_together=set([('route', 'stop', 'date')]),
        ),
    ]
