# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-27 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busshaming', '0041_auto_20181127_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routestopday',
            name='schedule_wait_time_seconds_avg',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='routestopday',
            name='schedule_wait_time_seconds_total',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='routestophour',
            name='expected_random_wait_time_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routestophour',
            name='realtime_random_wait_time_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
