# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-27 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busshaming', '0042_auto_20181127_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripdate',
            name='sum_delay_squared',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
