# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-03 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busshaming', '0043_auto_20181127_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedtimetable',
            name='processed_watermark',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
